### ISSUE TITLE
Session' object has no attribute 'remove'

### ISSUE THREAD

**Issue by sergiogiuffrida** [patriz/falcon-rest-api#1]
2017-02-17 20:04:21 +0000] [23879] [ERROR] Error handling request /v1/users/self/login?email=test1@gmail.com&password=test1234
Traceback (most recent call last):
  File "/home//Project/python/sysops_restapi/.venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home//Project/python/sysops_restapi/.venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home//Project/python/sysops_restapi/.venv/lib/python3.5/site-packages/falcon/api.py", line 226, in __call__
    process_response(req, resp, resource, req_succeeded)
  File "/home//Project/python/sysops_restapi/.venv/lib/python3.5/site-packages/falcon/api_helpers.py", line 63, in shim
    process_response(req, resp, resource)
  File "/home//Project/python/sysops_restapi/app/middleware/session_manager.py", line 41, in process_response
    session.remove()
AttributeError: 'Session' object has no attribute 'remove'

Like the official documentation the remove method is deprecated.

**Comment by ziwon** [comment]
Sorry for my late reply. I didn't know at all that there was an issue registered on this repo. 

You're right. So I fixed this issue by calling remove on `Session` not `session`.
Thank you for informing me about the error.
