### ISSUE TITLE
KeyError when hitting the /v1/users endpoint

### ISSUE THREAD

**Issue by hbutau** [patriz/falcon-rest-api#10]

**Comment by hbutau** [comment]
Hello @ziwon , I am getting the following error when hitting the v1/users/ endpoint:
 `Traceback (most recent call last):
  File "falcon/api.py", line 289, in falcon.api.API.__call__
  File "falcon/api.py", line 286, in falcon.api.API.__call__
  File "./app/middleware/session_manager.py", line 29, in process_response
    session = req.context["session"]
  File "falcon/util/structures.py", line 151, in falcon.util.structures.Context.__getitem__
KeyError: 'session'
[pid: 12515|app: 0|req: 1/1] 127.0.0.1 () {30 vars in 437 bytes} [Tue Jul  2 12:13:10 2019] GET /v1/users => generated 0 bytes in 51 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
`

**Comment by hbutau** [comment]
Closed.
